# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  version:
    description: 'Documentation version number'
    required: true
    default: 'TODO'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}