name: "Deploy docs on main"
on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version
        id: version
        run: |
          version=$(cat version)
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Build documentation
        id: hello
        uses: diasdm/action-versioned-sphinx-docs@main
        with:
          version: ${{ steps.version.outputs.version }}
